#!/bin/sh

run(){
    eval "su - nginx -s /bin/ash -c 'cd /var/www/drupal/ && "$@"'" 
    return $? 
}

if [ -f /tmp/drupal_configured ] && [ $(cat /tmp/drupal_configured) -eq 0 ]
then
    run vendor/bin/drush cron
fi
