#!/usr/bin/with-contenv sh

run(){
    eval "su - nginx -s /bin/ash -c 'cd /var/www/drupal/ && "$@"'" 
    return $? 
}

install(){
    echo "> Install"
    if [ ! -d /var/www/drupal ] 
    then
        echo ">>> No volume mounted"
        mkdir -p /var/www/drupal
        chown nginx:nginx /var/www/drupal
    fi
    cd /var/www/drupal/
    INSTALLED=$( run composer info 2>/dev/null | grep "drupal/drupal" )
    if [ -z "$INSTALLED" ];
    then
        echo ">>> Installing"
        run $( echo composer create-project drupal-composer/drupal-project:${DRUPAL_VERSION} /tmp/tmpdrupal --prefer-dist --no-interaction --no-dev  --quiet ) || return 1

        mv /tmp/tmpdrupal/* /tmp/drupal/.*  /var/www/drupal/  2>/dev/null 
        rm -R /tmp/tmpdrupal
        
    else
        echo ">>> Already Installed"
    fi

    return 0
}



config(){

    echo "> Config"
    echo ">>> Waiting for database to be ready"
    while  ! $( nc -vz ${DATABASE_HOST} ${DATABASE_PORT} ) ;
    do
            sleep 1
    done
    cd /var/www/drupal/
    CONFIG=$(run vendor/bin/drush status bootstrap | grep Successful)

    if [ -z "$CONFIG" ];
    then 
        echo ">>> Configuring"
        echo y | run $( echo 'vendor/bin/drush site-install --db-url="mysql://'${DRUPAL_DB_USERNAME}':'${DRUPAL_DB_PASSWORD}'@'${DATABASE_HOST}':'${DATABASE_PORT}'/'${DRUPAL_DB_NAME}'" --account-name="'${ADMIN_USERNAME}'" --account-pass="'${ADMIN_PASSWORD}'" --account-mail="'${ADMIN_EMAIL}'" --site-name="'${SITE_NAME}'" --site-mail="'${ADMIN_EMAIL}'" ') || return 1
        echo ">>> Disable web cron"
        run vendor/bin/drush -y vset cron_safe_threshold 0
    else
        echo ">>> Already Configured"
    fi

    return 0


}



fail(){
  echo "[ Failed ]"
  echo "1" > /tmp/drupal
  return 1

}

success(){
  echo "[ Success ]"
  echo "0" > /tmp/drupal
  return 0

}


install && config && success || fail

